### PR TITLE
rest: Serialize errors as string

### PR DESCRIPTION
**Pull request by bmoylan**
Fixes https://github.com/palantir/witchcraft-go-server/issues/27

cc @kmblake

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/30)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/30)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bmoylan and @nmiyake)

___
*[rest/handlers.go, line 54 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/30#-LWrIF3IBgfJTO0B-IFe:-LWrIF3IBgfJTO0B-IFf:bsfdfnh) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ee91515185caf8d0c9f6480b7ed8879487a04182/rest/handlers.go#L54)):*
> ```Go
> 		h.handleError(r.Context(), status, err)
> 		var jsonErr interface{}
> 		if um, ok := err.(json.Marshaler); ok {
> ```

What is the `um` variable here? If it's random, then would prefer better name.

**Review by bmoylan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/30)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nmiyake)

___
*[rest/handlers.go, line 54 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/30#-LWrIF3IBgfJTO0B-IFe:-LWrKpSu82euAwlFrqv6:b-e9hcn4) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ee91515185caf8d0c9f6480b7ed8879487a04182/rest/handlers.go#L54)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

What is the `um` variable here? If it's random, then would prefer better name.
</blockquote></details>

heh it was for `unmarshaler`which is also wrong. fixed

**Review by nmiyake — CHANGES_REQUESTED** [review]
Thanks -- logic/content looks good, but some feedback on tests.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/30#-:-LWrN4qG0lxm5q_rUWvQ:bde2fml)* status: all files reviewed, 2 unresolved discussions (waiting on @bmoylan)

___
*[rest/rest_test.go, line 24 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/30#-LWrMoJb06fRZ1VTEojv:-LWrMoJb06fRZ1VTEojw:b-fzbwie) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/e15f8fb70124f2b620540488268d4093b214a2cc/rest/rest_test.go#L24)):*
> ```Go
> 
> 	"github.com/palantir/witchcraft-go-error"
> 	_ "github.com/palantir/witchcraft-go-logging/wlog-zap"
> ```

Prefer not adding this import for a test that does not need to log/test logging
___
*[rest/rest_test.go, line 52 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/30#-LWrMsh36lWke7TLk63E:-LWrMsh36lWke7TLk63F:bscotcx) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/e15f8fb70124f2b620540488268d4093b214a2cc/rest/rest_test.go#L52)):*
> ```Go
> 			server := httptest.NewServer(rest.NewJSONHandler(func(http.ResponseWriter, *http.Request) error {
> 				return test.Err
> 			}, rest.StatusCodeMapper, rest.ErrHandler))
> ```

Prefer that the last parameter be `nil` rather than `rest.ErrHandler` so that running the tests does not produce any output (`rest.ErrHandler` performs service logging, so right now a successful run of the test still produces output)

**Review by nmiyake — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/30)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
