### PR TITLE
Add a health check based on a sliding window of errors

### PR DESCRIPTION
**Pull request by splucs**
Part 3 of https://github.com/palantir/witchcraft-go-server/issues/113

Added two health checks based on a sliding window of errors. Each with a common error-to-check policy.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/116)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/116)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @nmiyake and @splucs)

___
*[status/health/window/error_source.go, line 39 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoW9XfAdJlWPfI83QC:-LpoW9XfAdJlWPfI83QD:b5m6e7f) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0ae816d2e710cd0ec0056bec1ef8c5916b55832f/status/health/window/error_source.go#L39)):*
> ```Go
> // with a sliding window of size windowSize and uses the checkType.
> // windowSize must be a positive value, otherwise returns error.
> func NewUnhealthyIfAtLeastOneErrorSource(windowSize time.Duration, checkType health.CheckType) (*UnhealthyIfAtLeastOneErrorSource, error) {
> ```

I think API reads a bit better when `checkType` is first -- that's typically a more "core" piece of information than the duration.
___
*[status/health/window/error_source.go, line 50 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoWIWO7Gdgdcjh0q7T:-LpoWIWO7Gdgdcjh0q7U:bm87h99) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0ae816d2e710cd0ec0056bec1ef8c5916b55832f/status/health/window/error_source.go#L50)):*
> ```Go
> }
> 
> // Submit submits an error to the TimeWindowedStore.
> ```

Don't think this comment is needed. If you want to keep it, then remove reference to `TimeWindowedStore` (it's an internal implementation detail so no need to include it in documentation of exported API)
___
*[status/health/window/error_source.go, line 51 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoWhcYBq-6leTdPMn0:-LpoWhcYBq-6leTdPMn1:b-j2e7to) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0ae816d2e710cd0ec0056bec1ef8c5916b55832f/status/health/window/error_source.go#L51)):*
> ```Go
> 
> // Submit submits an error to the TimeWindowedStore.
> func (u *UnhealthyIfAtLeastOneErrorSource) SubmitError(err error) {
> ```

Would `Record` make more sense than `Submit`?

**Review by splucs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/116)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @nmiyake)

___
*[status/health/window/error_source.go, line 39 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoW9XfAdJlWPfI83QC:-LpoYM0g8yfrztdzKpbm:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0ae816d2e710cd0ec0056bec1ef8c5916b55832f/status/health/window/error_source.go#L39)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

I think API reads a bit better when `checkType` is first -- that's typically a more "core" piece of information than the duration.
</blockquote></details>

Done.
___
*[status/health/window/error_source.go, line 50 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoWIWO7Gdgdcjh0q7T:-LpoYLqv7S5hOkUjUtQU:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0ae816d2e710cd0ec0056bec1ef8c5916b55832f/status/health/window/error_source.go#L50)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Don't think this comment is needed. If you want to keep it, then remove reference to `TimeWindowedStore` (it's an internal implementation detail so no need to include it in documentation of exported API)
</blockquote></details>

Done.
___
*[status/health/window/error_source.go, line 51 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoWhcYBq-6leTdPMn0:-LpoYJDfD45huwl2o1Xi:boeu2qk) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/0ae816d2e710cd0ec0056bec1ef8c5916b55832f/status/health/window/error_source.go#L51)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Would `Record` make more sense than `Submit`?
</blockquote></details>

I don't think it makes a difference.

**Review by nmiyake — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/116)* status: all files reviewed, 1 unresolved discussion (waiting on @splucs)

___
*[status/health/window/error_source.go, line 50 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoZHaf-gtssqGtjsYz:-LpoZHagDGMjSZ1SY8N1:bolinhu) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/8b5e7ef72075420840df45818a60594d9db210b5/status/health/window/error_source.go#L50)):*
> ```Go
> }
> 
> // Submit submits an error.
> ```

Not really worth changing as part of the PR, but in general would say that there's no point in including a comment like this -- if a comment doesn't add any information that can't be gleamed from the signature, then it's not really worth including.

**Review by splucs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/116)* status: all files reviewed, 1 unresolved discussion (waiting on @nmiyake)

___
*[status/health/window/error_source.go, line 50 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/116#-LpoZHaf-gtssqGtjsYz:-LpoZhV26p3bPs1tgicX:br8pp8z) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/8b5e7ef72075420840df45818a60594d9db210b5/status/health/window/error_source.go#L50)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Not really worth changing as part of the PR, but in general would say that there's no point in including a comment like this -- if a comment doesn't add any information that can't be gleamed from the signature, then it's not really worth including.
</blockquote></details>

I believe golint requires a comment.

**Pull request merged**
