### PR TITLE
Do not require ECV key if there are no encrypted values

### LINKED ISSUE #25: Do not require ECV key if there are no encrypted values

### PR DESCRIPTION
**Pull request by bmoylan**
Fixes #25

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/28)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
Thanks! As part of this, can you add a bit of clarification to the README as well? Right now, the README states:

```
witchcraft-server also supports using encrypted-config-value to automatically decrypt encrypted configuration values. The default configuration expects a key file to be at var/conf/encrypted-config-value.key. It is possible to use code to specify a different source for the key (or to specify that no key should be used).
```

I think we should add a section afterwards that describes the other aspects of the behavior:
* If an ECV key file does not exist at the config path on startup, no ECV key is used
* It is acceptable to run with no ECV key defined as long as the neither the install nor runtime config contain encrypted values
* If the server does not have an ECV key defined and encounters any config with encrypted values, it will be treated as an error condition

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/28#-:-LWlgUQYBvvfruypuXur:b21kl9z)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[integration/config_test.go, line 32 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/28#-LWleYzo21m94XHNVOTm:-LWleYzp0xhcoH6TR38r:bpvpro9) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9c06ba55f421e58cbee12ca9f956b41e9dadc794/integration/config_test.go#L32)):*
> ```Go
> 
> func TestEncryptedConfig(t *testing.T) {
> 	decryptedValue := "hello world"
> ```

Since these are all string constants, prefer declaring as constants in block notation here:

```go
const (
    decryptedValue = "hello world"
    ...
)
```

**Comment by nmiyake** [comment]
Thanks! Implementation looks good -- only request is to add some documentation on the behavior.

**Review by bmoylan — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/28#-:-LWlsNQ40r2sUJoDOItN:bb7f2mf)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @nmiyake)

___
*[integration/config_test.go, line 32 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/28#-LWleYzo21m94XHNVOTm:-LWlsOSD8XEQRLyGhhhA:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/9c06ba55f421e58cbee12ca9f956b41e9dadc794/integration/config_test.go#L32)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Since these are all string constants, prefer declaring as constants in block notation here:

```go
const (
    decryptedValue = "hello world"
    ...
)
```
</blockquote></details>

Done.

**Review by nmiyake — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/28)* status: all files reviewed, 1 unresolved discussion (waiting on @nmiyake)

**Review by nmiyake — APPROVED** [review]

**Pull request merged**
