### PR TITLE
Fix health source "last success" behavior

### LINKED ISSUE #89: Period health check does not behave as documented
The polling health check source does not behave as documented.

Based on the documentation (and from what I can garner from the code/messages), if a health check returns "healthy", then even if it returns a non-healthy state after that, the over-all health should still be reported as "healthy" as long as the last "healthy" status was within the grace period.

As currently implemented, if a non-success status is returned after a success status, the "last success" status is not preserved, and the check incorrectly reports that there were no successful checks during the grace period.

### PR DESCRIPTION
**Pull request by nmiyake**
Ensure that, if the check has returned a healthy status within
the grace period, the over-all check returns healthy.

Fixes #89

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/90)

### CODE REVIEW

**Review by bmoylan — APPROVED** [review]
Wow, thanks nick :man_facepalming: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/90#-:-LgkQ1mmCXtXRnXHDlMO:bxwsqha)* status: all files reviewed, 1 unresolved discussion (waiting on @gregakinman and @nmiyake)

___
*[status/health/periodic/source_test.go, line 367 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/90#-LgkPQfVEw44PivIHQFU:-LgkPQfVEw44PivIHQFV:b-2it61i) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/64e1aca2b302bd31498ecbf58781495f70b32bf9/status/health/periodic/source_test.go#L367)):*
> ```Go
> 				}()
> 
> 				if counter == 0 {
> ```

I'd probably make these cases a `switch` statement but don't consider it blocking

**Review by nmiyake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/90)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bmoylan and @gregakinman)

___
*[status/health/periodic/source_test.go, line 367 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/90#-LgkPQfVEw44PivIHQFU:-Lgmgs7-5Cn-9JkshQ1p:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/64e1aca2b302bd31498ecbf58781495f70b32bf9/status/health/periodic/source_test.go#L367)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

I'd probably make these cases a `switch` statement but don't consider it blocking
</blockquote></details>

Done.

**Review by bmoylan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/90#-:-LgmhA8jEXIvB1hvWJ20:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregakinman)

**Comment by nmiyake** [comment]
Looks like there may be some timing issues with the test -- working on making that behavior more deterministic now and will open PR that fixes test.

**Comment by nmiyake** [comment]
Tracked this down -- caused by #91. Opened #92 to fix.

**Pull request merged**
