### PR TITLE
Shutdown server on SIGTERM

### PR DESCRIPTION
**Pull request by najork**
Fixes https://github.com/palantir/witchcraft-go-server/issues/59

This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61)

### CODE REVIEW

**Review by bmoylan — CHANGES_REQUESTED** [review]
Thanks for submitting! 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-:-LbdMPcWE_M8jeI8cEZP:bw0tsge)* status: all files reviewed, 2 unresolved discussions (waiting on @najork)

___
*[witchcraft/witchcraft.go, line 706 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdMSJD7x-E2GVjWZw1:-LbdMSJD7x-E2GVjWZw2:bwoi35a) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/cfcef11f84996839c3b9c563a8d76899f392ef29/witchcraft/witchcraft.go#L706)):*
> ```Go
> func (s *Server) initSigtermHandler(ctx context.Context) {
> 	sigterm := make(chan os.Signal, 1)
> 	signal.Notify(sigterm, syscall.SIGTERM)
> ```

Let's also catch `SIGINT` here
___
*[witchcraft/witchcraft.go, line 710 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdM6hhDU_O95uG79Ii:-LbdM6hhDU_O95uG79Ij:bd1ziky) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/cfcef11f84996839c3b9c563a8d76899f392ef29/witchcraft/witchcraft.go#L710)):*
From https://golang.org/pkg/net/http/#Server.Shutdown:
> When Shutdown is called, Serve, ListenAndServe, and ListenAndServeTLS immediately return ErrServerClosed. Make sure the program doesn't exit and waits instead for Shutdown to return.

We need to track whether or not `Shutdown` has been called and add an extra blocking condition to the end of `Start()`. We don't want to hang forever if the shutdown is triggered a different way (setup returns an error, someone calls `Close()`, etc) so maybe we introduce a [WaitGroup](https://golang.org/pkg/sync/#WaitGroup) and increment it in `Shutdown` then defer a `Wait`

**Review by najork — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bmoylan)

___
*[witchcraft/witchcraft.go, line 706 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdMSJD7x-E2GVjWZw1:-LbdPiEw8oZVTelTHGmb:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/cfcef11f84996839c3b9c563a8d76899f392ef29/witchcraft/witchcraft.go#L706)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Let's also catch `SIGINT` here
</blockquote></details>

Done.
___
*[witchcraft/witchcraft.go, line 710 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdM6hhDU_O95uG79Ii:-LbdQ5wZ-c7ypOxbeIbT:b-rah7p1) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/cfcef11f84996839c3b9c563a8d76899f392ef29/witchcraft/witchcraft.go#L710)):*
I'm not sure whether I fully understand this comment. The godoc on [witchcraft.Start](https://github.com/palantir/witchcraft-go-server/blob/develop/witchcraft/witchcraft.go#L419) states:
> Start begins serving HTTPS traffic and blocks until s.Close() or s.Shutdown() are called.

Are we changing the behavior to block until `s.Shutdown()` returns?

**Review by bmoylan — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61)* status: all files reviewed, 1 unresolved discussion (waiting on @najork)

___
*[witchcraft/witchcraft.go, line 710 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdM6hhDU_O95uG79Ii:-LbdSX4k202K9fpQmWaK:b-wj1xe1) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/cfcef11f84996839c3b9c563a8d76899f392ef29/witchcraft/witchcraft.go#L710)):*
<details><summary><i>Previously, najork (Max Najork) wrote…</i></summary><blockquote>

I'm not sure whether I fully understand this comment. The godoc on [witchcraft.Start](https://github.com/palantir/witchcraft-go-server/blob/develop/witchcraft/witchcraft.go#L419) states:
> Start begins serving HTTPS traffic and blocks until s.Close() or s.Shutdown() are called.

Are we changing the behavior to block until `s.Shutdown()` returns?

</blockquote></details>

Yeah, so the last line of `Start()` wraps `ListenAndServeTLS`, which blocks while the server is running. As written, this will return when Shutdown is **called**, which does not allow time for graceful connection draining. Instead we need to wait for Shutdown to **return** before `Start` returns, since most applications will exit immediately after Start. 

I mentioned the thing about the WaitGroup because there are multiple ways the server could be closed. Otherwise I'd just add a `shutdownFinished chan struct{}` to `*Server` and `defer func() { <-s.shutdownFinished }` or something

**Review by bmoylan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61)* status: all files reviewed, 3 unresolved discussions (waiting on @najork)

*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdU0Ah7E8QWaDr-fmi:-LbdU0Ah7E8QWaDr-fmj:b2r5vr7) (no related file):*
Can you add a section to the README explaining this feature?

---
*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdU2zE0XlFyC1XEsks:-LbdU2zE0XlFyC1XEskt:b-nw8sa1) (no related file):*
We should probably have a `.WithDisableShutdownSignals` option that turns this off just in case

---

**Review by najork — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @bmoylan)

*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdU0Ah7E8QWaDr-fmi:-Lbdngx8BOXOBYGc7_C7:b-896fix) (no related file):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Can you add a section to the README explaining this feature?
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdU2zE0XlFyC1XEsks:-LbdnhR6CRAkB4nzE8Hb:b-896fix) (no related file):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

We should probably have a `.WithDisableShutdownSignals` option that turns this off just in case
</blockquote></details>

Done.

---
___
*[witchcraft/witchcraft.go, line 710 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-LbdM6hhDU_O95uG79Ii:-LbdngCyD7vj9_eE08OH:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/cfcef11f84996839c3b9c563a8d76899f392ef29/witchcraft/witchcraft.go#L710)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Yeah, so the last line of `Start()` wraps `ListenAndServeTLS`, which blocks while the server is running. As written, this will return when Shutdown is **called**, which does not allow time for graceful connection draining. Instead we need to wait for Shutdown to **return** before `Start` returns, since most applications will exit immediately after Start. 

I mentioned the thing about the WaitGroup because there are multiple ways the server could be closed. Otherwise I'd just add a `shutdownFinished chan struct{}` to `*Server` and `defer func() { <-s.shutdownFinished }` or something
</blockquote></details>

Done.

**Comment by bmoylan** [comment]
Looks good! 

Can we add a test that 
- starts a server with a slow endpoint (e.g. something that sleeps for a second)
- client makes a request
- test calls shutdown
- ensure client eventually receives a valid response

**Comment by najork** [comment]
I believe this behavior should be covered by https://github.com/palantir/witchcraft-go-server/blob/develop/integration/server_test.go#L59

**Review by bmoylan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/61#-:-LbeTMOL7wol-EX5YgCP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
