### PR TITLE
Add a base sliding window health check

### PR DESCRIPTION
**Pull request by splucs**
Part two of https://github.com/palantir/witchcraft-go-server/issues/113

Adds a health check that takes in a function from items to health check and attaches it to a time windowed store to produce a health check source.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: all files reviewed, 2 unresolved discussions (waiting on @splucs)

___
*[status/health/window/base_source.go, line 44 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoQ4CHE8r0-tvkQvOS:-LpoQ4CHE8r0-tvkQvOT:btsfb6t) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L44)):*
> ```Go
> 	if err != nil {
> 		return nil, err
> 	}
> ```

This function should also return an error if `itemsToCheckFn == nil` (otherwise, `HealthStatus` will panic in that case)
___
*[status/health/window/base_source.go, line 58 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoPp_D-XZJo0iMtFCU:-LpoPp_D-XZJo0iMtFCV:b-7m6uiq) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L58)):*
> ```Go
> // HealthStatus polls the TimeWindowedStore and creates a HealthStatus using the ItemsToCheckFn.
> func (b *BaseHealthCheckSource) HealthStatus(ctx context.Context) health.HealthStatus {
> 	checkResult := b.itemsToCheckFn(ctx, b.timeWindowedStore.ItemsInWindow())
> ```

Just inline in assignment:

```
checkResult.Type: 	b.itemsToCheckFn(ctx, b.timeWindowedStore.ItemsInWindow())
```

**Review by splucs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: all files reviewed, 2 unresolved discussions (waiting on @nmiyake)

___
*[status/health/window/base_source.go, line 44 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoQ4CHE8r0-tvkQvOS:-LpoQgC21BtuNajL_lSE:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L44)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This function should also return an error if `itemsToCheckFn == nil` (otherwise, `HealthStatus` will panic in that case)
</blockquote></details>

Done.
___
*[status/health/window/base_source.go, line 58 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoPp_D-XZJo0iMtFCU:-LpoQggk9YhvWHiVZk_8:b-e74dx2) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L58)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Just inline in assignment:

```
checkResult.Type: 	b.itemsToCheckFn(ctx, b.timeWindowedStore.ItemsInWindow())
```
</blockquote></details>

checkType is fetched from checkResult, so we can inline this

**Review by splucs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nmiyake)

___
*[status/health/window/base_source.go, line 58 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoPp_D-XZJo0iMtFCU:-LpoRiUa0BMt7c2rahVW:b-dtkp2) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L58)):*
<details><summary><i>Previously, splucs (Lucas França de Oliveira) wrote…</i></summary><blockquote>

checkType is fetched from checkResult, so we can inline this
</blockquote></details>

we can't*

**Review by nmiyake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: all files reviewed, 2 unresolved discussions (waiting on @splucs)

___
*[status/health/window/base_source.go, line 58 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoPp_D-XZJo0iMtFCU:-LpoSkJH9icgnXVAr9Kj:b-m46fmm) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L58)):*
<details><summary><i>Previously, splucs (Lucas França de Oliveira) wrote…</i></summary><blockquote>

we can't*
</blockquote></details>

Ah right, I see -- got it!
___
*[status/health/window/base_source.go, line 42 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoSbhV29tESpRs4ESZ:-LpoSbhV29tESpRs4ES_:b-yzq60i) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/c54b0874786a0eb550e45f134ce1674457e2c6da/status/health/window/base_source.go#L42)):*
> ```Go
> // windowSize must be a positive value and itemsToCheckFn must not be nil, otherwise returns error.
> func NewBaseHealthCheckSource(windowSize time.Duration, itemsToCheckFn ItemsToCheckFn) (*BaseHealthCheckSource, error) {
> 	if itemsToCheckFn == nil {
> ```

nit: parameters should be checked in the order they are provided (so `windowSize` validation should happen before validation for `itemsToCheckFn`)

**Review by splucs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nmiyake)

___
*[status/health/window/base_source.go, line 58 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoPp_D-XZJo0iMtFCU:-LpoT4Zb6Dw76j55L7XE:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/69a0bd8032ed465ed3d98501ef9e1bd076bcabf0/status/health/window/base_source.go#L58)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Ah right, I see -- got it!
</blockquote></details>

Done.

**Review by nmiyake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: all files reviewed, 1 unresolved discussion (waiting on @splucs)

___
*[status/health/window/base_source.go, line 47 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoTCmxDjqYN8e_71MM:-LpoTCmxDjqYN8e_71MN:b-nuw47z) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/23117a7f9c9509d3978bbc4e6cb9d38a70bb38b7/status/health/window/base_source.go#L47)):*
> ```Go
> 	}
> 	if itemsToCheckFn == nil {
> 		return nil, werror.Error("itemsToCheckFn is nil")
> ```

Sorry, should have caught this the first time -- message should be `itemsToCheckFn cannot be nil` or `itemsToCheckFn must be non-nil`

**Review by splucs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nmiyake)

___
*[status/health/window/base_source.go, line 47 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-server/115#-LpoTCmxDjqYN8e_71MM:-LpoUep7CbGHMY5hMccw:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/23117a7f9c9509d3978bbc4e6cb9d38a70bb38b7/status/health/window/base_source.go#L47)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Sorry, should have caught this the first time -- message should be `itemsToCheckFn cannot be nil` or `itemsToCheckFn must be non-nil`
</blockquote></details>

Done.

**Review by nmiyake — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/115)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
