### PR TITLE
Make default refreshable threadsafe

### PR DESCRIPTION
**Pull request by bmoylan**
// opening for Adam

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76)

### CODE REVIEW

**Review by bmoylan — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76)* status: all files reviewed, 2 unresolved discussions

___
*[witchcraft/refreshable/refreshable_default.go, line 25 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-Lf6UcQLDdJGAh5FUchY:-Lf6UcQLDdJGAh5FUchZ:b-r6c0cn) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/e367108976b6435b10c62ff04f04620904d0873e/witchcraft/refreshable/refreshable_default.go#L25)):*
> ```Go
> 
> type DefaultRefreshable struct {
> 	sync.Mutex
> ```

Let's use a `RWMutex` so multiple readers can read at the same time
___
*[witchcraft/refreshable/refreshable_default.go, line 60 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-Lf6Uhj40wEZvvCCRm0R:-Lf6Uhj40wEZvvCCRm0S:brs4z9h) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/e367108976b6435b10c62ff04f04620904d0873e/witchcraft/refreshable/refreshable_default.go#L60)):*
> ```Go
> 
> func (d *DefaultRefreshable) Current() interface{} {
> 	d.Lock()
> ```

RLock and RUnlock

**Review by bmoylan — COMMENTED** [review]
:lgtm:

@nmiyake could you take a quick peek and make sure we're not missing something obvious here?

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-:-Lf6VY9U0yKXWVBFWCdm:b-j6zte2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by nmiyake — CHANGES_REQUESTED** [review]
Is there a link to an issue that demonstrates what this is trying to solve? At first blush, I feel like it might make more sense to protect the access outside the object itself (although this is more of an instinct/feeling, as I can't point to a concrete scenario in which the current approach is necessarily bad/incorrect).

Marking as blocked until discussion is resolved, but if it is sufficiently resolved we may proceed without changing the PR.

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-:-Lf6ixhaCrUjq3ElMA2d:b-age0ah)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by nmiyake — CHANGES_REQUESTED** [review]
Synced offline and concern seems to be around synchronizing access, and that seems reasonable.

Question about whether locking also needs to happen for the `Map` function.

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-:-LfMQQ5v7ardFp2V1MfE:b858wsv)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[witchcraft/refreshable/refreshable_default.go, line 93 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-LfMQG2IEuXbUNhGueKp:-LfMQG2IEuXbUNhGueKq:b50qxb0) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/420a0874bb40bf5bf12fd97d13bb1fa7fd094330/witchcraft/refreshable/refreshable_default.go#L93)):*
> ```Go
> 
> func (d *DefaultRefreshable) Map(mapFn func(interface{}) interface{}) Refreshable {
> 	newRefreshable := NewDefaultRefreshable(mapFn(d.current))
> ```

Should the `d.current` be replaced with `d.Current()` instead so that it uses the lock/unlock defined there?

**Review by asanderson15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bmoylan and @nmiyake)

___
*[witchcraft/refreshable/refreshable_default.go, line 93 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-LfMQG2IEuXbUNhGueKp:-LfQhDqn5gMuk4FytthA:b9wj7t8) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/420a0874bb40bf5bf12fd97d13bb1fa7fd094330/witchcraft/refreshable/refreshable_default.go#L93)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Should the `d.current` be replaced with `d.Current()` instead so that it uses the lock/unlock defined there?
</blockquote></details>

Yes, that's a good catch. Done.

**Review by nmiyake — COMMENTED** [review]
OK, based on discussions :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76#-:-LfVDciR6I7C5A75AdQd:b-rld7k)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bmoylan and @nmiyake)

**Review by nmiyake — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bmoylan — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/76)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
