### PR TITLE
Add configuration field for trace-sample-rate

### PR DESCRIPTION
**Pull request by bmoylan**
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/65)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
The code structure looks good, but have concerns about the sampling algorithm/logic.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/65#-:-Lc7ekPG-3w_uJgNYDcw:b-nrov2u)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[witchcraft/witchcraft.go, line 833 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/65#-Lc7ciTcCvSvO35j1-gO:-Lc7ciTcCvSvO35j1-gP:b-fgj5yg) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/d58e6cc5cbf823bdf3f537d56a17604b7ffce5d6/witchcraft/witchcraft.go#L833)):*
> ```Go
> 	}
> 	return func(id uint64) bool {
> 		mod := uint64(1 / sampleRate)
> ```

I believe this is too coarse.

For example, if `sampleRate` is set to `0.9` ("sample 90%"), `1/sampleRate` = 1.111, which turns into 1, which then effectively becomes a 100% sample rate.

I believe that scaling the maximal value of `uint64` based on the input ratio and comparing the ID to that would be a better approach -- for example, https://github.com/openzipkin/zipkin/blob/a40ebcb47986ed1efb85a0543a17611d78404eb2/zipkin-collector/core/src/main/java/zipkin2/collector/CollectorSampler.java#L68.

As noted in the comment there, the approach may not be statistically perfect, but is likely good enough.

**Comment by MatthewMaclean** [comment]
👍  from me

**Comment by nmiyake** [comment]
Need to run `format`

**Review by bmoylan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/65)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/trace_test.go, line 27 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/65#-Lc7oyw99h8PaRm-6fte:-Lc7oyw99h8PaRm-6ftf:b-m2gzph) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/31d1ad8ef9e0620dc85f917e795a2bb73690d887/witchcraft/trace_test.go#L27)):*
> ```Go
> 	for _, test := range []struct {
> 		rate     float64
> 		expected [16]bool
> ```

let me know if you have a cleaner way to write this test...
___
*[witchcraft/witchcraft.go, line 833 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/65#-Lc7ciTcCvSvO35j1-gO:-Lc7ovUcBpj3QIrmjfsn:b-trrfty) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/d58e6cc5cbf823bdf3f537d56a17604b7ffce5d6/witchcraft/witchcraft.go#L833)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

I believe this is too coarse.

For example, if `sampleRate` is set to `0.9` ("sample 90%"), `1/sampleRate` = 1.111, which turns into 1, which then effectively becomes a 100% sample rate.

I believe that scaling the maximal value of `uint64` based on the input ratio and comparing the ID to that would be a better approach -- for example, https://github.com/openzipkin/zipkin/blob/a40ebcb47986ed1efb85a0543a17611d78404eb2/zipkin-collector/core/src/main/java/zipkin2/collector/CollectorSampler.java#L68.

As noted in the comment there, the approach may not be statistically perfect, but is likely good enough.
</blockquote></details>

Done! You are totally correct.

**Review by nmiyake — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/65)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[witchcraft/trace_test.go, line 27 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/65#-Lc7oyw99h8PaRm-6fte:-Lc7pOKI1s68DVNyqvgS:bm733od) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/31d1ad8ef9e0620dc85f917e795a2bb73690d887/witchcraft/trace_test.go#L27)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

let me know if you have a cleaner way to write this test...
</blockquote></details>

I think this is good -- provides decent coverage of the cases, and it's targeted enough that I don't think it's worth any extra effort to specifically decomp other things (like specifying range of bools without explicitly doing the arrays).

**Review by nmiyake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/65)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

**Review by nmiyake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/65)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

**Pull request merged**
