### PR TITLE
Fix: minor code cleanup for health status polling

### PR DESCRIPTION
**Pull request by nmiyake**
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/88)

### CODE REVIEW

**Review by bmoylan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/88)* status: all files reviewed, 1 unresolved discussion (waiting on @gregakinman and @nmiyake)

___
*[status/health/periodic/source.go, line 115 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/88#-LgivWYH-vBZnhwVfdQU:-LgivWYH-vBZnhwVfdQV:boh6u3v) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/585e4072d7d3732ec36e52380ef6030a9567d217/status/health/periodic/source.go#L115)):*
> ```Go
> 	for {
> 		select {
> 		case <-ctx.Done():
> ```

The reason for this select statement is that if both the context is cancelled and the ticker has fired, we do not want to call doPoll with a cancelled context (the below select will nondeterministically choose one)

**Review by nmiyake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/88)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan and @gregakinman)

___
*[status/health/periodic/source.go, line 115 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/88#-LgivWYH-vBZnhwVfdQU:-Lgj5v596SqZCXprujo8:b10541u) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/585e4072d7d3732ec36e52380ef6030a9567d217/status/health/periodic/source.go#L115)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

The reason for this select statement is that if both the context is cancelled and the ticker has fired, we do not want to call doPoll with a cancelled context (the below select will nondeterministically choose one)
</blockquote></details>

OK. As written, this actually doesn't do that (it only decreases the probability of that occurring by a very small amount). Will amend PR to address the case you described.

**Review by bmoylan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/88#-:-Lgj6_Y80y7wGigy50rb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregakinman)

___
*[status/health/periodic/source.go, line 115 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/88#-LgivWYH-vBZnhwVfdQU:-Lgj6UhCEXx191dc8NUS:b-ucfknh) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/585e4072d7d3732ec36e52380ef6030a9567d217/status/health/periodic/source.go#L115)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

OK. As written, this actually doesn't do that (it only decreases the probability of that occurring by a very small amount). Will amend PR to address the case you described.
</blockquote></details>

Thanks!

**Comment by nmiyake** [comment]
Tests failing -- will look into it

**Comment by nmiyake** [comment]
Hmm looks like that failing test may be flaky -- passes locally and passed when I re-triggered build.

**Comment by nmiyake** [comment]
@bmoylan I believe this should be ready for review again, as the test failure appears to be unrelated to the change.

**Review by bmoylan — APPROVED** [review]

**Pull request merged**
