### PR TITLE
Improvement: use logging.sls metric to track logger usage

### PR DESCRIPTION
**Pull request by ch-plattner**
## Before this PR
Witchcraft-go-servers do not currently emit metrics about the SLS logs produced.

As part of the go infra tooling week, we are adding this functionality.

## After this PR
==COMMIT_MSG==
This PR adds a metric-recording svclogger to the WGS.
==COMMIT_MSG==

## Possible downsides?
Given that we will be recording metrics with each log, it may be possible that we see a slight perf decrease in logging. We will monitor for this both in units tests and in production when we wire in all of the metric-recording loggers.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
Approach looks good -- some feedback on the specifics.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-:-M6X8rn349jiB28GBbTb:b7w9tua)* status: all files reviewed, 7 unresolved discussions (waiting on @ch-plattner)

___
*[witchcraft/witchcraft.go, line 606 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X5m8fE7UcRDdKqVTC:-M6X5m8fE7UcRDdKqVTD:bwdfch8) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/witchcraft.go#L606)):*
> ```Go
> 	ctx = metrics.WithRegistry(ctx, metricsRegistry)
> 
> 	// wrap loggers with metric emitting log wrappers
> ```

Is there a reason that this commented out?
___
*[witchcraft/internal/metricloggers/emitter.go, line 26 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X6KVF19SasmzMzIF6:-M6X6KVF19SasmzMzIF7:b-z7zxzs) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L26)):*
> ```Go
> )
> 
> type MetricEmitter interface {
> ```

nit: I think "MetricRecorder" or something along those lines would be better naming, since that's what the interface captures. "Emit" in terms of metrics also has a more specific meaning (the periodic task that dumps all the metrics to disk), so would also be good not to overload that.
___
*[witchcraft/internal/metricloggers/emitter.go, line 27 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X8juD4ERiA4YhbYT5:-M6X8juD4ERiA4YhbYT6:b-8170cr) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L27)):*
> ```Go
> 
> type MetricEmitter interface {
> 	MarkSLSLog(typ string, level string)
> ```

Should include documentation for function
___
*[witchcraft/internal/metricloggers/emitter.go, line 34 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X6kjuDEwP84CJTdeL:-M6X6kjuDEwP84CJTdeM:b-v1opsy) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L34)):*
> ```Go
> }
> 
> func NewMetricEmitter(registry metrics.RootRegistry) MetricEmitter {
> ```

The argument should be a `metrics.Registry` since it's a subset of `metrics.RootRegistry` and we don't need any root-registry-specific functions
___
*[witchcraft/internal/metricloggers/emitter.go, line 40 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X6zQH2dQxFnvhDl74:-M6X6zQH2dQxFnvhDl75:bsjkd9z) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L40)):*
> ```Go
> func (m *metricEmitter) MarkSLSLog(typ string, level string) {
> 	m.registry.Meter(slsLoggingMeterName,
> 		metrics.MustNewTag("type", svc1log.TypeValue),
> ```

The value should be `typ` rather than `svc1log.TypeValue`
___
*[witchcraft/internal/metricloggers/emitter.go, line 41 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X8PNQDpgm1Sc_7R0T:-M6X8PNQDpgm1Sc_7R0U:bnk7nmo) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L41)):*
> ```Go
> 	m.registry.Meter(slsLoggingMeterName,
> 		metrics.MustNewTag("type", svc1log.TypeValue),
> 		metrics.MustNewTag("level", level)).Mark(1)
> ```

This will panic if the level value is empty, which I believe it is expected to be for non-service loggers (based on reading code and looking at metrics reported in Datadog)
___
*[witchcraft/internal/metricloggers/svclogger.go, line 37 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X5spB2-d7qRcsyKRx:-M6X5spB2-d7qRcsyKRy:b-dp7w9q) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/svclogger.go#L37)):*
> ```Go
> 
> func (m *metricEmittingSvcLogger) Debug(msg string, params ...svc1log.Param) {
> 	m.emitter.MarkSLSLog(svc1log.TypeValue, svc1log.LevelDebugValue)
> ```

Although it shouldn't matter too much in practice, I think we should record the metric after calling the delegate implementation rather than before.

**Review by ch-plattner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/witchcraft.go, line 606 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X5m8fE7UcRDdKqVTC:-M6_OJxt7_5SuxP80pYF:bis8whz) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/witchcraft.go#L606)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Is there a reason that this commented out?
</blockquote></details>

Ah, I should have left a note. I wanted to show an example of how to use the new loggers and where to put them, but actually overwriting the loggers was causing tests to fail. I think it's best to wire them all in at once when all of the metric loggers are done. I'll go ahead and delete the commented out code for now.
___
*[witchcraft/internal/metricloggers/emitter.go, line 26 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X6KVF19SasmzMzIF6:-M6_OG6G6gy0_BUKLzWn:b432pam) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L26)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

nit: I think "MetricRecorder" or something along those lines would be better naming, since that's what the interface captures. "Emit" in terms of metrics also has a more specific meaning (the periodic task that dumps all the metrics to disk), so would also be good not to overload that.
</blockquote></details>

That's helpful, thanks! Will change
___
*[witchcraft/internal/metricloggers/emitter.go, line 27 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X8juD4ERiA4YhbYT5:-M6_Uxxz9vErf-szPdUM:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L27)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Should include documentation for function
</blockquote></details>

Done.
___
*[witchcraft/internal/metricloggers/emitter.go, line 34 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X6kjuDEwP84CJTdeL:-M6_OE1R0r9jmoII8Hy9:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L34)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

The argument should be a `metrics.Registry` since it's a subset of `metrics.RootRegistry` and we don't need any root-registry-specific functions
</blockquote></details>

Done.
___
*[witchcraft/internal/metricloggers/emitter.go, line 40 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X6zQH2dQxFnvhDl74:-M6_O9W95jgzGIwE5F1s:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L40)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

The value should be `typ` rather than `svc1log.TypeValue`
</blockquote></details>

Done.
___
*[witchcraft/internal/metricloggers/emitter.go, line 41 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X8PNQDpgm1Sc_7R0T:-M6_NlpZCM_AC9bo3OQI:b-pk3q15) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/emitter.go#L41)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This will panic if the level value is empty, which I believe it is expected to be for non-service loggers (based on reading code and looking at metrics reported in Datadog)
</blockquote></details>

Ah, okay I didn't realize that! I'll add some checks for that
___
*[witchcraft/internal/metricloggers/svclogger.go, line 37 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6X5spB2-d7qRcsyKRx:-M6_NelBEVml6NbXOHIv:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27cba7b48ff25953d7666ed71f995d02e92bd2da/witchcraft/internal/metricloggers/svclogger.go#L37)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Although it shouldn't matter too much in practice, I think we should record the metric after calling the delegate implementation rather than before.
</blockquote></details>

Done.

**Comment by ashrayjain** [comment]
@ch-plattner would be great to include some info about what this change is about and why it's worth adding in the PR description :)

**Review by nmiyake — CHANGES_REQUESTED** [review]
Good flag @ashrayjain -- we opened this to discuss implementation for an infra-week feature, but agree that should have been made more clear in the initial PR to signal to all people watching.

We'll update PR to properly include this context before final review (and for future PRs that are for initial iteration/feedback only, we'll note that in the initial submission comments)

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-:-M6_eiXG7_pPo-JrVMDq:b-ip6cui)* status: all files reviewed, 2 unresolved discussions (waiting on @ch-plattner)

___
*[witchcraft/internal/metricloggers/emitter.go, line 25 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_eZdt1w975PqgEgcl:-M6_eZdt1w975PqgEgcm:b-z3wctg) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/1f488eaf463299b47420db3dc2a512e53f2861e8/witchcraft/internal/metricloggers/emitter.go#L25)):*
> ```Go
> )
> 
> type MetricRecorder interface {
> ```

Will all of the consumers/users of this interface be in the `metricloggers` package? If so, would be better not to export the interface.
___
*[witchcraft/internal/metricloggers/emitter.go, line 37 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_e8Cp4vi4hj8AjK5C:-M6_e8Cp4vi4hj8AjK5D:bjw2ut2) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/1f488eaf463299b47420db3dc2a512e53f2861e8/witchcraft/internal/metricloggers/emitter.go#L37)):*
> ```Go
> }
> 
> // RecordSLSLog increments the count of the SLS logging metric
> ```

Let's move this comment to the interface function declaration.

The general way I think about this is that the interface functions should have the documentation that describes the contract for the function (the behavior that is expected/required of any implementor of the interface).

If there are implementation details that are helpful to know about the particular implementation details of an interface function, then those are appropriate to have as comments on the implementation of the function.

**Review by ch-plattner — COMMENTED** [review]
I updated the PR header to include a link to the infra ticket! @nmiyake do you think I should go ahead and add the benchmarks for this svclogger as part of this PR, or should we do those later?

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-:-M6_ms6gBBHldct_qZEj:bpatr34)* status: all files reviewed, 2 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/internal/metricloggers/emitter.go, line 25 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_eZdt1w975PqgEgcl:-M6_l30vBPQnBQd54haz:b-zfnjem) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/1f488eaf463299b47420db3dc2a512e53f2861e8/witchcraft/internal/metricloggers/emitter.go#L25)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Will all of the consumers/users of this interface be in the `metricloggers` package? If so, would be better not to export the interface.
</blockquote></details>

Yep, you're right. Keeping it internal sounds good.
___
*[witchcraft/internal/metricloggers/emitter.go, line 37 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_e8Cp4vi4hj8AjK5C:-M6_mlXqCdahM183VXns:b7rd7on) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/1f488eaf463299b47420db3dc2a512e53f2861e8/witchcraft/internal/metricloggers/emitter.go#L37)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Let's move this comment to the interface function declaration.

The general way I think about this is that the interface functions should have the documentation that describes the contract for the function (the behavior that is expected/required of any implementor of the interface).

If there are implementation details that are helpful to know about the particular implementation details of an interface function, then those are appropriate to have as comments on the implementation of the function.
</blockquote></details>

Great, that makes sense. I'll go ahead and move the comment.

**Review by nmiyake — CHANGES_REQUESTED** [review]
Thanks, I think this looks good!

Going to have as "block" rather than publish because I think the change we merge should include using this and tests.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-:-M6_s9qxCq8plSvvoOrw:bs81ets)* status: all files reviewed, 1 unresolved discussion (waiting on @ch-plattner)

___
*[witchcraft/internal/metricloggers/recorder.go, line 44 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_rLAgEkOaFsmMDI4I:-M6_rLAh1fvOQp4sR8h9:b-yialm7) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/b87db51f85e28f5c7450d8289f099d629f1d0786/witchcraft/internal/metricloggers/recorder.go#L44)):*
> ```Go
> 		metrics.MustNewTag("type", typ),
> 	}
> 	if len(level) > 0 {
> ```

This is very much a nit and doesn't need to be changed, but in my experience it's slightly more canonical Go style to have `level != ""` as the test case for empty strings (I think part of that is that looking at that comparison immediately makes it apparent that `level` is a string, versus this construction which may be used for `map` or slice as well).

**Comment by nmiyake** [comment]
Updated PR with implementation that uses the instrumenting logger wrapper -- ready for review.

**Review by ch-plattner — COMMENTED** [review]
Nick, this looks great. I like how the metrics recorder ultimately turned out. Left one small comment

> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-:-M6aTwMmDjT4QKH9mtyM:b-82rcuo)* status: all files reviewed, 3 unresolved discussions (waiting on @nmiyake)

___
*[witchcraft/internal/metricloggers/recorder.go, line 44 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_rLAgEkOaFsmMDI4I:-M6aQcbU9I3E_Wh0c3HT:b-qrxx1t) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/b87db51f85e28f5c7450d8289f099d629f1d0786/witchcraft/internal/metricloggers/recorder.go#L44)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This is very much a nit and doesn't need to be changed, but in my experience it's slightly more canonical Go style to have `level != ""` as the test case for empty strings (I think part of that is that looking at that comparison immediately makes it apparent that `level` is a string, versus this construction which may be used for `map` or slice as well).
</blockquote></details>

Think this is resolved now that we have separate functions!
___
*[witchcraft/internal/metricloggers/recorder.go, line 41 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6aRWrCCqwOGJXHjNMg:-M6aRWrCCqwOGJXHjNMh:bg44eni) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27f037af1f57e9d1fc7b99cd0da707dc567fe4a4/witchcraft/internal/metricloggers/recorder.go#L41)):*
> ```Go
> }
> 
> type metricRecorder interface {
> ```

Great, this is wrapped up quite nicely
___
*[witchcraft/internal/metricloggers/recorder.go, line 46 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6aRmYvDGbDxpdZl2ld:-M6aRmYvDGbDxpdZl2le:bwq6dgo) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27f037af1f57e9d1fc7b99cd0da707dc567fe4a4/witchcraft/internal/metricloggers/recorder.go#L46)):*
> ```Go
> 
> 	// RecordSLSLog increments the count of the SLS logging metric for the given log type and log level.
> 	// If level is empty, it will be omitted from the recorded metric.
> ```

nit: can delete this caveat now that its not relevant

**Review by nmiyake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179)* status: all files reviewed, 3 unresolved discussions (waiting on @ch-plattner)

___
*[witchcraft/internal/metricloggers/recorder.go, line 44 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6_rLAgEkOaFsmMDI4I:-M6aee-B4IJRnjWqBxls:b3bzqlw) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/b87db51f85e28f5c7450d8289f099d629f1d0786/witchcraft/internal/metricloggers/recorder.go#L44)):*
<details><summary><i>Previously, ch-plattner (Char) wrote…</i></summary><blockquote>

Think this is resolved now that we have separate functions!
</blockquote></details>

Ah, although that's true, we are back at a place where the function will panic if the value is empty. However, that's also true if the value is anything that can't be parsed as a tag, and since the value is now a type I think it's reasonable to only support the enumerated values for the type.

I'll update the documentation on the interface function to make this clear.
___
*[witchcraft/internal/metricloggers/recorder.go, line 46 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6aRmYvDGbDxpdZl2ld:-M6aesjP7mIaVJ9mtyzB:b-6gh71u) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27f037af1f57e9d1fc7b99cd0da707dc567fe4a4/witchcraft/internal/metricloggers/recorder.go#L46)):*
<details><summary><i>Previously, ch-plattner (Char) wrote…</i></summary><blockquote>

nit: can delete this caveat now that its not relevant
</blockquote></details>

Thanks! Per comment below, I think the documentation should actually still have a caveat, but with our implementation update should be about supported values (and that function may panic if an unsupported value is provided).

**Review by ch-plattner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-:-M6agTve306iwhiaTyva:bnfp4nl)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @ch-plattner and @nmiyake)

___
*[witchcraft/internal/metricloggers/recorder.go, line 46 at r5](https://reviewable.io/reviews/palantir/witchcraft-go-server/179#-M6aRmYvDGbDxpdZl2ld:-M6agG5w0eiXpQbQ7eiZ:bknq6d) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/27f037af1f57e9d1fc7b99cd0da707dc567fe4a4/witchcraft/internal/metricloggers/recorder.go#L46)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Thanks! Per comment below, I think the documentation should actually still have a caveat, but with our implementation update should be about supported values (and that function may panic if an unsupported value is provided).
</blockquote></details>

Yep, I think changing the warning to something along those lines sounds good

**Review by ch-plattner — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179)* status: all files reviewed, 2 unresolved discussions (waiting on @nmiyake)

**Comment by ch-plattner** [comment]
👍 !

**Review by nmiyake — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/179)* status: all files reviewed, 1 unresolved discussion (waiting on @nmiyake)

**Comment by nmiyake** [comment]
Ran the benchmarks added in #180 on my local machine, and produced the following:

## Before this change (no logging metrics)
goos: darwin
goarch: amd64
pkg: github.com/palantir/witchcraft-go-server/witchcraft
BenchmarkServer_Loggers/svc1log-12         	  463544	      2487 ns/op
BenchmarkServer_Loggers/evt2log-12         	  756598	      1617 ns/op
BenchmarkServer_Loggers/metric1log-12      	  701541	      1736 ns/op
BenchmarkServer_Loggers/trc1log-12         	  629956	      1707 ns/op
BenchmarkServer_Loggers/audit2log-12       	  609351	      1668 ns/op
PASS

## After this change (with logging metrics)
goos: darwin
goarch: amd64
pkg: github.com/palantir/witchcraft-go-server/witchcraft
BenchmarkServer_Loggers/svc1log-12         	  373077	      2924 ns/op
BenchmarkServer_Loggers/evt2log-12         	  500991	      2151 ns/op
BenchmarkServer_Loggers/metric1log-12      	  456610	      2276 ns/op
BenchmarkServer_Loggers/trc1log-12         	  489609	      2223 ns/op
BenchmarkServer_Loggers/audit2log-12       	  472820	      2194 ns/op
PASS

It looks like it's adding about 500ns. It's a good data point to have, but for now I think we're good to proceed and monitor as needed.

**Pull request merged**
