### PR TITLE
Default to console logging even when running in non-Docker containers

### PR DESCRIPTION
**Pull request by ashrayjain**
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/80)

### CODE REVIEW

**Review by bmoylan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/80)* status: all files reviewed, 2 unresolved discussions (waiting on @ashrayjain)

*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-server/80#-Lg2rOrZ3coqHVDoPd09:-Lg2rOr_68hcfLgsOjCg:b-73srtf) (no related file):*
Please add this to the README docs regarding logging

---
___
*[witchcraft/loggers.go, line 86 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-server/80#-Lg2rT5hEosWkrYN6vMR:-Lg2rT5hEosWkrYN6vMS:b-n28ol5) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/36b41a4237e8ac1fbbb845d225b78500f9af497a/witchcraft/loggers.go#L86)):*
> ```Go
> 
> func isRunningInContainer() bool {
> 	_, ok := os.LookupEnv("CONTAINER")
> ```

is this a standard thing or something our internal infrastructure is setting?

**Comment by ashrayjain** [comment]
It's something our internal infra sets up

**Comment by gdearment** [comment]
@ashrayjain  - what do you want to do with this?

**Comment by ashrayjain** [comment]
When we switched internally from Docker -> containerd, we lost logging across a lot of services because of this.

We would like to have a way of having server infrastructure be best-effort smart about whether they are running inside a container or not.

There is a better/more resilient path forward that figures this out by looking at `/proc/1/cgroup` but I think we deemed that to be too "hacky" :D

**Comment by bmoylan** [comment]
Closing this in favor of #205

**Pull request closed without merging**
