### PR TITLE
Add ability to configure server's router implementation

### PR DESCRIPTION
**Pull request by nmiyake**
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/42)

### CODE REVIEW

**Comment by nmiyake** [comment]
Creating this PR mainly for feedback on concept and API. We can hold off on merging until I have a more fleshed out example of how this would be used by a program that needs to configure this aspect of the server.

**Review by bmoylan — COMMENTED** [review]
Looks fine to me pending testing the API with a real service

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/42#-:-LZb7Tfr9xwf-hJ9EeNH:b6is0py)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by nmiyake** [comment]
Example usage of this API exists on an internal project that shows that this code works and is useful in that scenario.

**Review by bmoylan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/42#-:-L_JNIxr0wkdUZoDD-em:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
