### PR TITLE
Refactor periodic healthchecks

### PR DESCRIPTION
**Pull request by gregakinman**
Based off of https://github.com/palantir/witchcraft-go-server/pull/77, except this changes that to allow multiple checks in the same source (and adds a couple tests for that).

(I opened against develop since the diff is only about 100 lines bigger than it is to @bmoylan's branch. Don't really feel strongly either way about merging this into that branch and then that into develop vs. merging this into develop, happy to do whatever works best.)

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/81)

### CODE REVIEW

**Comment by gregakinman** [comment]
Apparently I don't have perms to request reviewers. Tagging @bmoylan @andybradshaw @ryanmcnamara from the original PR.

**Review by bmoylan — CHANGES_REQUESTED** [review]
looking good! just a couple of small comments

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-:-LgDgYdXAVw7IeIPXynC:bfgqhvv)* status: all files reviewed, 2 unresolved discussions (waiting on @gregakinman)

___
*[status/health/periodic/source.go, line 61 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-LgCjcrY8glIrnrTL7Iv:-LgCjcrY8glIrnrTL7Iw:b1sbkaj) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/a013a50c9ad3e697ee75cd8983f6190b207c8ed6/status/health/periodic/source.go#L61)):*
> ```Go
> // is cancelled if ctx is cancelled. If gracePeriod elapses without Check returning HEALTHY, the returned health check
> // source will give a health status of error. checkType is the key to be used in the health result returned by the
> // health check source.
> ```

this comment needs to be updated for the new Source type
___
*[status/health/periodic/source.go, line 86 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-LgCkWpk4GiVCmN9qGwa:-LgCkWpk4GiVCmN9qGwb:bxnu3bz) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/a013a50c9ad3e697ee75cd8983f6190b207c8ed6/status/health/periodic/source.go#L86)):*
> ```Go
> 				Message: stringPtr("Check has not yet run"),
> 			}
> 		} else {
> ```

nit: I'd `continue` at the end of the `if !ok` block so you don't need the `else`

https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow

**Comment by bmoylan** [comment]
___
*[status/health/periodic/source.go, line 29 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-LgDghFL7JQAdy4yTRL6:-LgDghFL7JQAdy4yTRL7:b2hbcp4) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/a013a50c9ad3e697ee75cd8983f6190b207c8ed6/status/health/periodic/source.go#L29)):*
> ```Go
> 
> type Source struct {
> 	Checks map[health.CheckType]func(ctx context.Context) (state health.HealthState, params map[string]interface{})
> ```

What do you think about defining a function type so this reads a little simpler
```go
type SourceFunc func(ctx context.Context) (state health.HealthState, params map[string]interface{})

type Source struct {
	Checks map[health.CheckType]SourceFunc
}
```

**Review by gregakinman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/81)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @bmoylan)

___
*[status/health/periodic/source.go, line 29 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-LgDghFL7JQAdy4yTRL6:-LgEEWKg5Xoys_Ry1kxJ:b-uzl25r) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/a013a50c9ad3e697ee75cd8983f6190b207c8ed6/status/health/periodic/source.go#L29)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

What do you think about defining a function type so this reads a little simpler
```go
type SourceFunc func(ctx context.Context) (state health.HealthState, params map[string]interface{})

type Source struct {
	Checks map[health.CheckType]SourceFunc
}
```
</blockquote></details>

I think positively. Though I would call it `CheckFunc` or something like that
___
*[status/health/periodic/source.go, line 61 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-LgCjcrY8glIrnrTL7Iv:-LgEFrk76BKJWUqmVSYF:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/a013a50c9ad3e697ee75cd8983f6190b207c8ed6/status/health/periodic/source.go#L61)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

this comment needs to be updated for the new Source type
</blockquote></details>

Done.
___
*[status/health/periodic/source.go, line 86 at r2](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-LgCkWpk4GiVCmN9qGwa:-LgEDmkt8xAEYyLhXg4O:b6nywk4) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/a013a50c9ad3e697ee75cd8983f6190b207c8ed6/status/health/periodic/source.go#L86)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

nit: I'd `continue` at the end of the `if !ok` block so you don't need the `else`

https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow
</blockquote></details>

oh right, forgot go doesn't like `else` :) i had it written like that in a previous state...

**Review by bmoylan — APPROVED** [review]
:lgtm:

Given this is additive and Ryan is ooto until Tuesday, I'm going to merge this and we can follow up on any feedback when he's back.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/81#-:-LgESrFq62RA2p2GRHM8:b-qck3ve)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by bmoylan** [comment]
updated in #82

**Pull request merged**
