### PR TITLE
Add use-wrapped-logs configuration to enable wrapped logging

### PR DESCRIPTION
**Pull request by advayakrishna**
## Before this PR

This change adds a WrappedLogger configuration to the base Install configuration to allow the server to output all logs in "wrapped.1" format.

When both EntityName and EntityVersion are specified in configuration, logs will be output in "wrapped.1" format.

## After this PR

==COMMIT_MSG==
Add WrappedLogger configuration to enable wrapped logging
==COMMIT_MSG==

## Possible downsides?

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/278)

### CODE REVIEW

**Review by bmoylan — CHANGES_REQUESTED** [review]
> Reviewed 28 of 31 files at r1, 2 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/278)* status: all files reviewed, 2 unresolved discussions (waiting on @advayakrishna)

___
*[witchcraft/loggers.go, line 55 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/278#-MXXfdG78sCdGQNzQtLB:-MXXfdG78sCdGQNzQtLC:b-vr9z5z) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ed508b1505f301ced20d1de57d9a4f29416e5feb/witchcraft/loggers.go#L55)):*
> ```Go
> 		if useWrappedLogs {
> 			// Wrapped five frames for wrapped logger
> 			originParam = svc1log.OriginFromCallLineWithSkip(5)
> ```

do/can we test this anywhere? it is very easy to break with innocuous refactoring
___
*[witchcraft/witchcraft.go, line 659 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/278#-MXXfyAi3nytqz41DaKY:-MXXfyAi3nytqz41DaKZ:b-cq5k1r) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ed508b1505f301ced20d1de57d9a4f29416e5feb/witchcraft/witchcraft.go#L659)):*
> ```Go
> 
> 		// re-initialize the loggers with the TCP writer and overwrite the context
> 		s.initLoggers(baseInstallCfg.UseConsoleLog, baseInstallCfg.UseWrappedLogs, baseInstallCfg.ProductName, baseInstallCfg.ProductVersion, wlog.InfoLevel, metricsRegistry, asyncTCPWriter)
> ```

hm, we explicitly don't want wrapped logging when shipping full envelopes over TCP (the spec doesn't allow it). The expectation is that the fields in the envelope are correct, even if they do not match the process that happened to write them. How should we handle this case?

**Review by advayakrishna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/278)* status: all files reviewed, 2 unresolved discussions (waiting on @bmoylan)

___
*[witchcraft/loggers.go, line 55 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/278#-MXXfdG78sCdGQNzQtLB:-MXYUEkW1xaQce2YtKcH:b6jsyfr) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ed508b1505f301ced20d1de57d9a4f29416e5feb/witchcraft/loggers.go#L55)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

do/can we test this anywhere? it is very easy to break with innocuous refactoring
</blockquote></details>

Will add a test case
___
*[witchcraft/witchcraft.go, line 659 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/278#-MXXfyAi3nytqz41DaKY:-MXYULI2-ULfqvitKskH:beo6wmc) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ed508b1505f301ced20d1de57d9a4f29416e5feb/witchcraft/witchcraft.go#L659)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

hm, we explicitly don't want wrapped logging when shipping full envelopes over TCP (the spec doesn't allow it). The expectation is that the fields in the envelope are correct, even if they do not match the process that happened to write them. How should we handle this case?
</blockquote></details>

I think we should log a warning and not use wrapped logs when the TCP writer is specified and wrapped logs are enabled. Feels like overkill to kill the server over this misconfiguration.

**Comment by bmoylan** [comment]
___
*[witchcraft/witchcraft.go, line 659 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/278#-MXXfyAi3nytqz41DaKY:-MXYqSbg7hvcktqc8gYA:bu08n39) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ed508b1505f301ced20d1de57d9a4f29416e5feb/witchcraft/witchcraft.go#L659)):*
<details><summary><i>Previously, advayakrishna (Advaya Krishna) wrote…</i></summary><blockquote>

I think we should log a warning and not use wrapped logs when the TCP writer is specified and wrapped logs are enabled. Feels like overkill to kill the server over this misconfiguration.
</blockquote></details>

Can we overwrite the two relevant fields in envelopeMetadata? If so, we don't need the warning :)

**Review by bmoylan — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/278)* status: all files reviewed, 1 unresolved discussion (waiting on @advayakrishna)

**Review by advayakrishna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/278)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan)

___
*[witchcraft/witchcraft.go, line 659 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-server/278#-MXXfyAi3nytqz41DaKY:-MXZ25gm0F06GX05hhQ4:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-server/blob/ed508b1505f301ced20d1de57d9a4f29416e5feb/witchcraft/witchcraft.go#L659)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Can we overwrite the two relevant fields in envelopeMetadata? If so, we don't need the warning :) 
</blockquote></details>

Done.

**Review by bmoylan — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-server/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @advayakrishna)

**Pull request merged**
